### ISSUE TITLE
"#" in  Library Report

### ISSUE THREAD

**Issue by darwin4ever** [boroda74/TagTools#1]
When I open a playlist, track-numbering starts at "1".

**TagTools Release 20190212**
When I include "#" in the "Additional Tagging Tools / Library Report" track-numbering did start at "0", so always 1 too low
**TagTools Release 20230211**
When I include "#" in the "Additional Tagging Tools / Library Report" "#" **doesn't output anything anymore**.

How come ? How to solve this ?

And I have a question too :
Can I specify somewhere the default target location for the exports of "Additional Tagging Tools / Library Report" ?

**Comment by boroda74** [comment]
1. # is not track number. It's just the number of current line. Actually, it's almost useless and I have never tested it well. To get track # use grouping "Track#". 
2. For now default location is always desktop, but I'll change this, so last exported folder will be default for new export.

**Comment by darwin4ever** [comment]
Hi,

In case of a Playlist # might be the number of the current line, BUT it 
is ALSO the track number in the playlist. Track# is always the original 
track numbers (from the original Source CD a.s.o)

So # is not useless at all (and it worked in the past) !

Kind regards

**Comment by boroda74** [comment]
You know? You are right! I've broken this during last refactoring because I've completely forgotten that even 1 predefined preset uses this feature. 

Last LR export folder is remembered now.

You can download the latest plugin version either here or on MB site.

**Comment by boroda74** [comment]
I think current "#" implementation won't do what you need. It doesn't preserve original lines order. I'll look at all this more closely tomorrow.

**Comment by boroda74** [comment]
I've tried to fix "#" ordering. From my testing, all is working fine now, but please test the latest version yourself more thoroughly.

**Comment by darwin4ever** [comment]
Hi,

Thank you very much, everything is working fine now, all issues solved 
(tested on a playlist) :

  * # is working now (when sorted on # but also when sorted on another
    field)
  * # counting from 1 now, no longer from zero
  * export destination path is remembered

Just a pity that the export-filename is always the last one used, and 
not remembered for every Preset

Kind regards

**Comment by boroda74** [comment]
>>Just a pity that the export-filename is always the last one used, and
>>not remembered for every Preset

Interesting idea. I think I'll make this.

**Comment by boroda74** [comment]
It's done. I'll close the issues if you confirm that all ok.

**Comment by darwin4ever** [comment]
Great .... and working just fine !
Thank you very much
